version: '3.1'

services:

  funding-db:
    image: postgres
    restart: always
    ports:
      - ${PG_FUNDING_PORT}:5432
    environment:
      POSTGRES_PASSWORD: ${PG_FUNDING_PASS}
      POSTGRES_USER: ${PG_FUNDING_USER}

networks:
  default:
    external:
      name: poc-wp
