version: '3.1'

services:

  onbaroding-db:
    image: postgres
    restart: always
    ports:
      - ${PG_ONBOARDING_PORT}:5432
    environment:
      POSTGRES_PASSWORD: ${PG_ONBOARDING_PASS}
      POSTGRES_USER: ${PG_ONBOARDING_USER}

networks:
  default:
    external:
      name: poc-wp
