version: '3.1'

services:

  clearing-db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: devdata
      POSTGRES_USER: devdata

networks:
  default:
    external:
      name: poc-wp
